# Generated by Django 4.2.20 on 2025-07-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=100, verbose_name='Номер акта исследования')),
                ('act_date', models.DateField(verbose_name='Дата акта исследования')),
                ('fault_bza', models.BooleanField(default=False, verbose_name='Виновник дефекта - БЗА')),
                ('guilty_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Виновное подразделение')),
                ('statistics_month', models.CharField(blank=True, max_length=20, null=True, verbose_name='Месяц отражения в статистике БЗА')),
                ('fault_consumer', models.BooleanField(default=False, verbose_name='Виновник дефекта - потребитель')),
                ('compliant_with_specs', models.BooleanField(default=False, verbose_name='Изделие соответствует ТУ')),
                ('fault_unknown', models.BooleanField(default=False, verbose_name='Виновник не установлен')),
                ('defect_causes', models.TextField(blank=True, null=True, verbose_name='Причины возникновения дефектов')),
                ('defect_causes_explanation', models.TextField(blank=True, null=True, verbose_name='Пояснения к причинам возникновения дефектов')),
                ('defective_supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поставщик дефектного комплектующего')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'db_table': 'investigation',
            },
        ),
    ]
