# Generated by Django 4.2.20 on 2025-07-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=100, verbose_name='Номер акта исследования')),
                ('act_date', models.DateField(verbose_name='Дата акта исследования')),
                ('fault_bza', models.BooleanField(default=False, verbose_name='Виновник дефекта - БЗА')),
                ('guilty_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Виновное подразделение')),
                ('fault_consumer', models.BooleanField(default=False, verbose_name='Виновник дефекта - потребитель')),
                ('compliant_with_specs', models.BooleanField(default=False, verbose_name='Изделие соответствует ТУ')),
                ('fault_unknown', models.BooleanField(default=False, verbose_name='Виновник не установлен')),
                ('defect_causes', models.TextField(blank=True, null=True, verbose_name='Причины возникновения дефектов')),
                ('defect_causes_explanation', models.TextField(blank=True, null=True, verbose_name='Пояснения к причинам возникновения дефектов')),
                ('defective_supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поставщик дефектного комплектующего')),
                ('pkd_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ПКД')),
                ('disposal_act_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта утилизации')),
                ('disposal_act_date', models.DateField(blank=True, null=True, verbose_name='Дата акта утилизации')),
                ('volume_removal_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер и месяц справки снятия с объёмов')),
                ('recipient', models.CharField(blank=True, max_length=200, null=True, verbose_name='Получатель')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки акта исследования')),
                ('shipment_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер накладной отгрузки изделия потребителю')),
                ('shipment_invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата накладной отгрузки изделия потребителю')),
                ('return_condition', models.CharField(blank=True, choices=[('REPAIRED', 'Отремонтировано'), ('REPLACED', 'Заменено на новое'), ('RETURNED_AS_IS', 'Возвращено как есть')], max_length=50, null=True, verbose_name='Состояние возвращаемого потребителю изделия')),
                ('return_condition_explanation', models.TextField(blank=True, null=True, verbose_name='Пояснения по состоянию возвращаемого изделия')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation', to='reclamations.reclamation', verbose_name='Рекламация')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'db_table': 'investigation',
                'indexes': [models.Index(fields=['act_number', 'act_date'], name='investigati_act_num_35719d_idx')],
            },
        ),
    ]
