# Generated by Django 4.2.20 on 2025-08-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_alter_reclamation_products_count_and_more'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='reclamation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation', to='reclamations.reclamation', verbose_name='ID рекламации'),
        ),
    ]
