# Generated by Django 4.2.20 on 2025-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_alter_investigation_reclamation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='compliant_with_specs',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='fault_bza',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='fault_consumer',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='fault_unknown',
        ),
        migrations.AddField(
            model_name='investigation',
            name='fault_type',
            field=models.CharField(choices=[('bza', 'БЗА'), ('consumer', 'Потребитель'), ('compliant', 'Соответствует ТУ'), ('unknown', 'Не установлен')], default='unknown', max_length=10, verbose_name='Виновник дефекта'),
            preserve_default=False,
        ),
    ]
