# Generated by Django 4.2.20 on 2025-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_remove_investigation_compliant_with_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='fault_type',
            field=models.CharField(choices=[('bza', 'БЗА'), ('consumer', 'Потребитель'), ('compliant', 'Соответствует ТУ'), ('unknown', 'Не установлен')], default='unknown', max_length=10, verbose_name='Виновник дефекта'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='guilty_department',
            field=models.CharField(default='Не определено', max_length=100, verbose_name='Виновное подразделение'),
        ),
    ]
