# Generated by Django 4.2.20 on 2025-08-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_alter_reclamation_products_count_and_more'),
        ('investigations', '0004_alter_investigation_fault_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='reclamation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation', to='reclamations.reclamation', verbose_name='Рекламация (ID и изделие)'),
        ),
    ]
