# Generated by Django 4.2.20 on 2025-08-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0005_alter_investigation_reclamation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'verbose_name': 'Акт исследования', 'verbose_name_plural': 'Акты исследования'},
        ),
    ]
