# Generated by Django 4.2.20 on 2025-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0006_alter_investigation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='act_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта исследования'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='act_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта исследования'),
        ),
    ]
