# Generated by Django 4.2.20 on 2025-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0007_alter_investigation_act_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='volume_removal_reference',
        ),
        migrations.AlterField(
            model_name='investigation',
            name='act_date',
            field=models.DateField(verbose_name='Дата акта исследования'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='act_number',
            field=models.CharField(max_length=100, verbose_name='Номер акта исследования'),
        ),
    ]
