# Generated by Django 4.2.20 on 2025-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0008_remove_investigation_volume_removal_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='defect_causes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Причины возникновения дефектов'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='defect_causes_explanation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пояснения к причинам возникновения дефектов'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='return_condition_explanation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пояснения по состоянию возвращаемого изделия'),
        ),
    ]
