# Generated by Django 4.2.20 on 2025-09-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0009_alter_investigation_defect_causes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='pkd_number',
        ),
    ]
