# Generated by Django 4.2.20 on 2025-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0010_remove_investigation_pkd_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='defect_causes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Причины дефекта'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='defect_causes_explanation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пояснения к причинам дефекта'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('REPAIRED', 'Отремонтировано'), ('REPLACED', 'Заменено на новое'), ('RETURNED_AS_IS', 'Возвращено как есть')], max_length=50, null=True, verbose_name='Состояние возвращаемого изделия'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='return_condition_explanation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пояснения к состоянию изделия'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='shipment_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата накладной отгрузки изделия'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='shipment_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладная отгрузки изделия'),
        ),
    ]
