# Generated by Django 4.2.20 on 2025-09-05 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0012_investigation_act_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='act_scan',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Разрешены только файлы PDF')], verbose_name='Копия акта исследования'),
        ),
    ]
