# Generated by Django 4.2.20 on 2025-09-07 20:18

from django.db import migrations, models
import investigations.models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0013_alter_investigation_act_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='act_number',
            field=models.CharField(default=investigations.models.get_default_act_number, max_length=100, verbose_name='Номер акта исследования'),
        ),
    ]
