# Generated by Django 4.2.20 on 2025-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0014_alter_investigation_act_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='solution',
            field=models.CharField(choices=[('ACCEPT', 'Признать'), ('DEFLECT', 'Отклонить')], max_length=50, null=True, verbose_name='Решение по рекламации'),
        ),
    ]
