# Generated by Django 4.2.20 on 2025-09-25 12:10

import django.core.validators
from django.db import migrations, models
import investigations.models
import investigations.storages


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0015_investigation_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='act_scan',
            field=models.FileField(blank=True, null=True, storage=investigations.storages.NoDuplicateFileStorage(), upload_to=investigations.models.investigation_act_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Разрешены только файлы PDF')], verbose_name='Копия акта исследования'),
        ),
    ]
