# Generated by Django 4.2.20 on 2025-11-12 19:24

from django.db import migrations, models
import re


def update_sort_values(apps, schema_editor):
    """Обновляет значения сортировки для существующих записей"""
    Investigation = apps.get_model("investigations", "Investigation")

    def calculate_sort_value(act_number):
        """Локальная функция для расчета значения сортировки"""
        act_num = act_number.strip() if act_number else ""

        if act_num == "не требуется":
            return -1.0

        match = re.search(r"(\d{4})\s*(?:№|ММЗ)\s*(\d+)(?:-(\d+))?", act_num)
        if match:
            year = int(match.group(1))  # 2025 (год)
            main_number = int(match.group(2))  # 1043
            suffix = int(match.group(3)) if match.group(3) else 0  # 0, 1 (суффикс)

            # Создаем дробное число: 2025,1043, 2025,104301
            return year + (main_number * 0.0001) + (suffix * 0.000001)
        else:
            return 0.0

    # Обновляем записи батчами для лучшей производительности
    batch_size = 100
    investigations = Investigation.objects.all()

    for i in range(0, investigations.count(), batch_size):
        batch = investigations[i : i + batch_size]
        updates = []

        for investigation in batch:
            investigation.act_number_sort = calculate_sort_value(
                investigation.act_number
            )
            updates.append(investigation)

        # Bulk update для лучшей производительности
        Investigation.objects.bulk_update(updates, ["act_number_sort"])


def reverse_update_sort_values(apps, schema_editor):
    """Обратная миграция - сбрасываем значения"""
    Investigation = apps.get_model("investigations", "Investigation")
    Investigation.objects.all().update(act_number_sort=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0016_alter_investigation_act_scan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigation",
            options={
                "ordering": ["-act_number_sort"],
                "verbose_name": "Акт исследования",
                "verbose_name_plural": "Акты исследования",
            },
        ),
        migrations.RemoveIndex(
            model_name="investigation",
            name="investigati_act_num_35719d_idx",
        ),
        migrations.AddField(
            model_name="investigation",
            name="act_number_sort",
            field=models.FloatField(
                default=0.0,
                help_text="Автоматически заполняется",
                verbose_name="Номер для сортировки",
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["-act_number_sort"], name="investigation_sort_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["act_date", "-act_number_sort"],
                name="investigation_date_sort_idx",
            ),
        ),
        migrations.RunPython(update_sort_values, reverse_update_sort_values),
    ]
