# Generated by Django 4.2.20 on 2025-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0017_alter_investigation_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investigation',
            name='investigation_date_sort_idx',
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['-act_number_sort', 'act_date'], name='investigation_date_sort_idx'),
        ),
    ]
