# Generated by Django 4.2.20 on 2025-07-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Период выявления дефекта')),
            ],
            options={
                'verbose_name': 'Период выявления дефекта',
                'verbose_name_plural': 'Периоды выявления дефектов',
                'db_table': 'period_defect',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
                'db_table': 'product_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=100, unique=True, verbose_name='Обозначение изделия')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sourcebook.producttype', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'product',
                'ordering': ['nomenclature'],
                'indexes': [models.Index(fields=['nomenclature'], name='product_nomencl_cfcd81_idx'), models.Index(fields=['product_type', 'nomenclature'], name='product_product_30a6e5_idx')],
            },
        ),
    ]
