# Generated by Django 4.2.20 on 2025-07-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Наименование изделия', 'verbose_name_plural': 'Наименования изделий'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sourcebook.producttype', verbose_name='Наименование изделия'),
        ),
    ]
