# Generated by Django 4.2.20 on 2025-07-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ претензии')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата претензии')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по претензии')),
                ('response_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ ответа БЗА')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа БЗА')),
                ('result', models.CharField(blank=True, choices=[('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена'), ('PARTIAL', 'Частично удовлетворена')], max_length=20, null=True, verbose_name='Результат рассмотрения претензии')),
                ('bza_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма затрат БЗА')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='reclamations.reclamation', verbose_name='Рекламация')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
                'db_table': 'claim',
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['number', 'date'], name='claim_number_f0a297_idx')],
            },
        ),
    ]
