# Generated by Django 4.2.20 on 2025-07-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='№ претензии')),
                ('date', models.DateField(verbose_name='Дата претензии')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по претензии')),
                ('response_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ ответа БЗА')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа БЗА')),
                ('result', models.CharField(blank=True, choices=[('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена'), ('PARTIAL', 'Частично удовлетворена'), ('PENDING', 'На рассмотрении')], max_length=20, null=True, verbose_name='Результат рассмотрения претензии')),
                ('bza_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма затрат БЗА')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
                'db_table': 'claim',
            },
        ),
    ]
