# Generated by Django 4.2.20 on 2025-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-claim_number'], 'verbose_name': 'Претензия', 'verbose_name_plural': 'Претензии'},
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_number_f0a297_idx',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='amount',
            new_name='claim_amount',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='date',
            new_name='claim_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='number',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер претензии'),
        ),
        migrations.AddField(
            model_name='claim',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ЮС регистрации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='bza_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Признанная сумма'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='response_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ответа БЗА'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='result',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена')], max_length=20, null=True, verbose_name='Результат рассмотрения'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number', 'claim_date'], name='claim_claim_n_0b0f08_idx'),
        ),
    ]
