# Generated by Django 4.2.20 on 2025-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_amount',
            new_name='claim_amount_all',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='bza_costs',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_amount_act',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по акту'),
        ),
        migrations.AddField(
            model_name='claim',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='claim',
            name='costs_act',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Признано по акту'),
        ),
        migrations.AddField(
            model_name='claim',
            name='costs_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Признано по претензии'),
        ),
        migrations.AddField(
            model_name='claim',
            name='investigation_act_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта исследования'),
        ),
        migrations.AddField(
            model_name='claim',
            name='investigation_act_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта исследования'),
        ),
        migrations.AddField(
            model_name='claim',
            name='reclamation_act_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта рекламации'),
        ),
        migrations.AddField(
            model_name='claim',
            name='reclamation_act_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта рекламации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(blank=True, default='009-11/ ', max_length=100, null=True, verbose_name='Номер ЮС регистрации'),
        ),
    ]
