# Generated by Django 4.2.20 on 2025-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_rename_claim_amount_claim_claim_amount_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='type_money',
            field=models.CharField(choices=[('RUR', 'RUR'), ('BYN', 'BYN')], default='RUR', max_length=10, null=True, verbose_name='Денежная единица'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(blank=True, default='009-11/', max_length=100, null=True, verbose_name='Номер ЮС регистрации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='result',
            field=models.CharField(choices=[('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена')], default='ACCEPTED', max_length=20, null=True, verbose_name='Результат рассмотрения'),
        ),
    ]
