# Generated by Django 4.2.20 on 2025-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_remove_claim_result_claim_investigation_act_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер двигателя'),
        ),
    ]
