# Generated by Django 4.2.20 on 2025-10-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0020_reclamation_reclamation_year_idx_and_more'),
        ('claims', '0006_claim_engine_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reclamation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='reclamations.reclamation', verbose_name='Рекламация'),
        ),
    ]
