# Generated by Django 4.2.20 on 2025-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claim_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='receipt_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладная прихода изделия'),
        ),
    ]
