# Generated by Django 4.2.20 on 2025-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_claim_receipt_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_amount_act',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по акту рекламации'),
        ),
    ]
