# Generated by Django 4.2.20 on 2025-10-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_alter_claim_investigation_act_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='claim',
            name='engine_number',
            field=models.CharField(blank=True, help_text='1. При положительном результе поиска поля формы заполнятся автоматически.\n   Переходите к регистрации претензии и заполнению формы далее.\n2. Если поля формы НЕ заполнились - нажмите СОХРАНИТЬ для получения результатов поиска\n   и добавьте комментарий для регистрации претензии.', max_length=100, null=True, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(blank=True, default='009-11/', max_length=100, null=True, verbose_name='Номер регистрации ЮС'),
        ),
    ]
