# Generated by Django 4.2.20 on 2025-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_remove_claim_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_amount_all',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_date',
            field=models.DateField(null=True, verbose_name='Дата претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='engine_number',
            field=models.CharField(blank=True, help_text='<li>При положительном результате поиска поля формы заполнятся автоматически.<br>Переходите к регистрации претензии и заполнению формы далее.</li><li>Если поля формы НЕ заполнились - нажмите СОХРАНИТЬ для получения результатов поиска<br>и добавьте комментарий для регистрации претензии.</li>', max_length=100, null=True, verbose_name='Номер двигателя'),
        ),
    ]
