# Generated by Django 4.2.20 on 2025-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_alter_claim_claim_amount_all_alter_claim_claim_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='message_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(blank=True, default='009-11/', max_length=100, null=True, verbose_name='Номер регистрации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ответа на претензию'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='response_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ответа на претензию'),
        ),
    ]
