# Generated by Django 4.2.20 on 2025-10-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0020_reclamation_reclamation_year_idx_and_more'),
        ('claims', '0014_alter_claim_message_received_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reclamations',
            field=models.ManyToManyField(blank=True, help_text='Рекламации, связанные с данной претензией', related_name='claims', to='reclamations.reclamation', verbose_name='Рекламации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_claims', to='reclamations.reclamation', verbose_name='Рекламация (старое)'),
        ),
    ]
