# Generated by Django 4.2.20 on 2025-10-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_migrate_reclamation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='reclamation',
        ),
    ]
