# Generated by Django 4.2.20 on 2025-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_remove_old_reclamation_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='consumer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Потребитель'),
        ),
    ]
