# Generated by Django 4.2.20 on 2025-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_fill_consumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='consumer_name',
            field=models.CharField(help_text='Заполняется автоматически или вручную (ЯМЗ, ММЗ, ПТЗ и т.д.)', max_length=100, verbose_name='Потребитель'),
        ),
    ]
