# Generated by Django 4.2.20 on 2025-10-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_alter_claim_consumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='investigation_act_date',
            field=models.DateField(blank=True, help_text='<li>При положительном результате поиска поля формы заполнятся автоматически.<br>Переходите к регистрации претензии и заполнению формы далее.</li><li>Если поля формы НЕ заполнились - нажмите СОХРАНИТЬ для получения результатов поиска<br>и добавьте комментарий для регистрации претензии.</li>', null=True, verbose_name='Дата акта исследования'),
        ),
    ]
