# Generated by Django 4.2.20 on 2025-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0021_alter_claim_engine_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-year', '-claim_number'], 'verbose_name': 'Претензия', 'verbose_name_plural': 'Претензии'},
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_claim_n_0b0f08_idx',
        ),
        migrations.AddField(
            model_name='claim',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Год претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amount_act',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма по акту рекламации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amount_all',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма по претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_date',
            field=models.DateField(verbose_name='Дата претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(max_length=100, verbose_name='Номер претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='registration_number',
            field=models.CharField(default='009-11/', help_text='Регистрационный номер ЮС в 2025 году', max_length=100, verbose_name='Номер регистрации'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='result_claim',
            field=models.CharField(choices=[('ACCEPTED', 'Принять'), ('REJECTED', 'Отклонить')], default='ACCEPTED', max_length=20, verbose_name='Решение по претензии'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type_money',
            field=models.CharField(choices=[('RUR', 'RUR'), ('BYN', 'BYN')], default='RUR', max_length=10, verbose_name='Денежная единица'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['year', 'claim_number', 'claim_date'], name='claim_year_b0835e_idx'),
        ),
    ]
