# Generated by Django 4.2.20 on 2025-07-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_brand', models.CharField(max_length=50, verbose_name='Марка двигателя')),
                ('engine_number', models.CharField(max_length=50, verbose_name='Номер двигателя')),
                ('transport_name', models.CharField(max_length=200, verbose_name='Транспортное средство')),
                ('transport_number', models.CharField(max_length=100, verbose_name='Номер транспортного средства')),
            ],
            options={
                'verbose_name': 'Двигатель и Транспортное средство',
                'verbose_name_plural': 'Двигатели и Транспортные средства',
                'db_table': 'engine_transport',
            },
        ),
        migrations.CreateModel(
            name='PeriodDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Период выявления дефекта')),
            ],
            options={
                'verbose_name': 'Период выявления дефекта',
                'verbose_name_plural': 'Период выявления дефектов',
                'db_table': 'period_defect',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
                'db_table': 'product_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=100, unique=True, verbose_name='Обозначение изделия')),
                ('product_number', models.CharField(max_length=10, verbose_name='Заводской номер изделия')),
                ('manufacture_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата изготовления изделия')),
                ('product_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'product',
                'ordering': ['nomenclature'],
                'unique_together': {('nomenclature', 'product_number')},
            },
        ),
    ]
