# Generated by Django 4.2.20 on 2025-07-25 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
        ('products', '0001_initial'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер рекламационного акта')),
                ('date', models.DateField(verbose_name='Дата рекламационного акта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_acts', to='products.perioddefect', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Рекламационный акт',
                'verbose_name_plural': 'Рекламационные акты',
                'db_table': 'reclamation_act',
                'unique_together': {('number', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_number', models.CharField(max_length=100, verbose_name='Входящий № по ОТК')),
                ('message_received_date', models.DateField(verbose_name='Дата поступления сообщения в ОТК')),
                ('sender', models.CharField(max_length=200, verbose_name='Кто отправил сообщение')),
                ('sender_outgoing_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исходящий № отправителя')),
                ('message_sent_date', models.DateField(blank=True, null=True, verbose_name='Дата отправления сообщения')),
                ('country_rejected', models.CharField(blank=True, max_length=100, null=True, verbose_name='Государство, где забраковано изделие')),
                ('purchaser', models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация-приобретатель')),
                ('end_consumer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Конечный потребитель')),
                ('consumer_act_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер рекламационного акта конечного потребителя')),
                ('consumer_act_date', models.DateField(blank=True, null=True, verbose_name='Дата рекламационного акта конечного потребителя')),
                ('defect_detection_date', models.DateField(blank=True, null=True, verbose_name='Дата выявления дефекта изделия')),
                ('mileage_operating_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пробег, наработка')),
                ('claimed_defect', models.TextField(verbose_name='Заявленный дефект изделия')),
                ('consumer_requirement', models.TextField(blank=True, null=True, verbose_name='Требование потребителя')),
                ('measures_taken', models.TextField(blank=True, null=True, verbose_name='Принятые меры по сообщению')),
                ('outgoing_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исходящий № документа')),
                ('outgoing_document_date', models.DateField(blank=True, null=True, verbose_name='Дата исходящего документа')),
                ('letter_sending_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Способ отправления письма по принятым мерам')),
                ('consumer_response', models.TextField(blank=True, null=True, verbose_name='Ответ потребителя на сообщение')),
                ('consumer_response_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исходящий № ответа потребителя')),
                ('consumer_response_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа потребителя')),
                ('product_received_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления изделия')),
                ('product_sender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация-отправитель изделия')),
                ('receipt_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер накладной прихода изделия')),
                ('receipt_invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата накладной прихода изделия')),
                ('products_quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество предъявленных изделий')),
                ('reclamation_documents', models.TextField(blank=True, null=True, verbose_name='Документы по рекламационному изделию')),
                ('pkd_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ПКД')),
                ('pkd_completion_mark', models.BooleanField(default=False, verbose_name='Отметка о выполнении ПКД')),
                ('disposal_act_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта утилизации')),
                ('disposal_act_date', models.DateField(blank=True, null=True, verbose_name='Дата акта утилизации')),
                ('volume_removal_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер и месяц справки снятия с объёмов')),
                ('recipient', models.CharField(blank=True, max_length=200, null=True, verbose_name='Получатель')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('shipment_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер накладной отгрузки изделия потребителю')),
                ('shipment_invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата накладной отгрузки изделия потребителю')),
                ('return_condition', models.CharField(blank=True, choices=[('REPAIRED', 'Отремонтировано'), ('REPLACED', 'Заменено на новое'), ('RETURNED_AS_IS', 'Возвращено как есть'), ('DISPOSED', 'Утилизировано')], max_length=50, null=True, verbose_name='Состояние возвращаемого потребителю изделия')),
                ('return_condition_explanation', models.TextField(blank=True, null=True, verbose_name='Пояснения по состоянию возвращаемого изделия')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('INVESTIGATION', 'На исследовании'), ('CLOSED', 'Закрыта')], default='NEW', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='claims.claim', verbose_name='Претензия')),
                ('defect_detection_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='products.perioddefect', verbose_name='Период выявления дефекта')),
                ('investigation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation', to='investigations.investigation', verbose_name='Исследование')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='products.product', verbose_name='Изделие')),
                ('purchaser_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaser_reclamations', to='reclamations.reclamationact', verbose_name='Рекламационный акт приобретателя')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='products.enginetransport', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'db_table': 'reclamation',
                'ordering': ['-message_received_date'],
            },
        ),
    ]
