# Generated by Django 4.2.20 on 2025-07-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Период выявления дефекта')),
            ],
            options={
                'verbose_name': 'Период выявления дефекта',
                'verbose_name_plural': 'Период выявления дефекта',
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=100, unique=True, verbose_name='Обозначение изделия')),
            ],
            options={
                'verbose_name': 'Обозначение изделия',
                'verbose_name_plural': 'Обозначение изделий',
                'db_table': 'product',
                'ordering': ['nomenclature'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Наименование изделия',
                'verbose_name_plural': 'Наименование изделий',
                'db_table': 'product_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamation_number', models.CharField(max_length=50, unique=True, verbose_name='Номер рекламации')),
                ('date_received', models.DateField(verbose_name='Дата получения')),
                ('defect_description', models.TextField(verbose_name='Описание дефекта')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('PROGRESS', 'В работе'), ('CLOSED', 'Закрыта')], default='NEW', max_length=50, verbose_name='Статус')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation', to='reclamations.organization', verbose_name='Организация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation', to='reclamations.product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'db_table': 'reclamation',
                'ordering': ['-date_received'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='reclamations.producttype', verbose_name='Наименование изделия'),
        ),
    ]
