# Generated by Django 4.2.20 on 2025-08-02 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='products_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество изделий'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'Исследование'), ('CLOSED', 'Закрыта')], default='NEW', max_length=50, verbose_name='Статус'),
        ),
    ]
