# Generated by Django 4.2.20 on 2025-08-05 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_alter_reclamation_products_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='claimed_defect',
            field=models.CharField(default='течь', max_length=250, verbose_name='Заявленный дефект изделия'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='consumer_requirement',
            field=models.CharField(blank=True, default='исследование', max_length=250, null=True, verbose_name='Требование потребителя'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='mileage_operating_time',
            field=models.CharField(max_length=100, verbose_name='Пробег, наработка'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='products_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество изделий'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='reclamation_documents',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документы по рекламационному изделию'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='sender',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кто отправил сообщение'),
        ),
    ]
