# Generated by Django 4.2.20 on 2025-08-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_reclamation_claimed_defect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='away_type',
            field=models.CharField(choices=[('notdata', 'н/д'), ('kilometre', 'км'), ('moto', 'м/ч')], default='notdata', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='mileage_operating_time',
            field=models.CharField(default='н/д', max_length=100, verbose_name='Пробег, наработка'),
        ),
    ]
