# Generated by Django 4.2.20 on 2025-08-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_reclamation_away_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='country_rejected',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Государство, где забраковано изделие'),
        ),
    ]
