# Generated by Django 4.2.20 on 2025-08-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_alter_reclamation_country_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-message_received_date'], 'verbose_name': 'Рекламацию', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
