# Generated by Django 4.2.20 on 2025-08-07 12:05

from django.db import migrations
import datetime


def convert_datetime_to_date(apps, schema_editor):
    Reclamation = apps.get_model('reclamations', 'Reclamation')

    for obj in Reclamation.objects.all():
        if not obj.message_received_date:
            continue

        # Если это datetime - конвертируем в date
        if isinstance(obj.message_received_date, datetime.datetime):
            obj.message_received_date = obj.message_received_date.date()
        # Если это уже date - оставляем как есть
        elif isinstance(obj.message_received_date, datetime.date):
            # Ничего не делаем, это уже правильный тип
            continue

        obj.save(update_fields=['message_received_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_alter_reclamation_options'),
    ]

    operations = [
        migrations.RunPython(convert_datetime_to_date),
    ]
