# Generated by Django 4.2.20 on 2025-08-07 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_auto_20250807_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='message_received_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления сообщения'),
        ),
    ]
