# Generated by Django 4.2.20 on 2025-08-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0008_alter_reclamation_message_received_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-id'], 'verbose_name': 'Рекламацию', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
