# Generated by Django 4.2.20 on 2025-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0009_alter_reclamation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='volume_removal_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер справки снятия с объёмов'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='reclamation_documents',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительные сведения по рекламации'),
        ),
    ]
