# Generated by Django 4.2.20 on 2025-08-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0010_reclamation_volume_removal_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='away_type',
            field=models.CharField(choices=[('notdata', 'н/д'), ('kilometre', 'км'), ('moto', 'м/ч'), ('psi', 'ПСИ')], default='notdata', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
