# Generated by Django 4.2.20 on 2025-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0011_alter_reclamation_away_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='consumer_response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ потребителя на сообщение'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='measures_taken',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Принятые меры по сообщению'),
        ),
    ]
