# Generated by Django 4.2.20 on 2025-09-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0012_alter_reclamation_consumer_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='pkd_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер 8D или ПКД'),
        ),
    ]
