# Generated by Django 4.2.20 on 2025-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0013_reclamation_pkd_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='pkd_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номерок 8D (ПКД)'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='receipt_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата накладной прихода'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='receipt_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладная прихода изделия'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'Исследование'), ('CLOSED', 'Закрыта')], default='NEW', max_length=50, verbose_name='Статус рекламации'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='volume_removal_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Справка снятия с объёмов'),
        ),
    ]
