# Generated by Django 4.2.20 on 2025-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0014_alter_reclamation_pkd_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='sender_outgoing_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исх. № отправителя (Номер ПСА)'),
        ),
    ]
