# Generated by Django 4.2.20 on 2025-09-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0015_alter_reclamation_sender_outgoing_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-id'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
