# Generated by Django 4.2.20 on 2025-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0016_alter_reclamation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='pkd_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номерок 8D (ПКД)'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='reclamation_documents',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Дополнительные сведения по рекламации'),
        ),
    ]
