# Generated by Django 4.2.20 on 2025-09-18 04:44

from django.db import migrations, models
from datetime import datetime


def populate_year_fields(apps, schema_editor):
    Reclamation = apps.get_model('reclamations', 'Reclamation')  # название приложения и модели

    current_year = datetime.now().year  # 2025

    for rec in Reclamation.objects.all():
        rec.year = current_year
        rec.yearly_number = rec.id
        rec.save()

    print(f"Обновлено {Reclamation.objects.count()} записей")

class Migration(migrations.Migration):
    dependencies = [
        ('reclamations', '0017_alter_reclamation_pkd_number_and_more'),  # предыдущая миграция
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='yearly_number',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_year_fields),
        migrations.AlterField(
            model_name='reclamation',
            name='year',
            field=models.IntegerField(verbose_name="Год рекламации"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='yearly_number',
            field=models.IntegerField(verbose_name="Номер в году"),
        ),
        migrations.AddConstraint(
            model_name='reclamation',
            constraint=models.UniqueConstraint(
                fields=['yearly_number', 'year'],
                name='unique_yearly_number'
            ),
        ),
    ]