# Generated by Django 4.2.20 on 2025-09-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0018_reclamation_year_reclamation_yearly_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reclamation',
            name='unique_yearly_number',
        ),
        migrations.AlterUniqueTogether(
            name='reclamation',
            unique_together={('yearly_number', 'year')},
        ),
    ]
