# Generated by Django 4.2.20 on 2025-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0019_remove_reclamation_unique_yearly_number_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['year'], name='reclamation_year_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['year', 'yearly_number'], name='reclamation_year_num_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['-year', '-yearly_number'], name='reclamation_order_idx'),
        ),
    ]
