# Generated by Django 4.2.20 on 2025-11-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0020_reclamation_reclamation_year_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='manufacture_date',
            field=models.CharField(blank=True, help_text='Данные вводите в формате ММ.ГГ или оставьте поле пустым', max_length=10, null=True, verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='product_number',
            field=models.CharField(blank=True, help_text='При отсутствии данных оставьте поле пустым', max_length=10, null=True, verbose_name='Номер изделия'),
        ),
    ]
