# Generated by Django 4.2.20 on 2025-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0021_alter_reclamation_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='consumer_response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ потребителя'),
        ),
    ]
