# Generated by Django 4.2.20 on 2025-09-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='Номер справки')),
                ('last_processed_id', models.PositiveIntegerField(verbose_name='ID последней записи')),
                ('report_date', models.DateField(verbose_name='Дата формирования справки')),
            ],
            options={
                'verbose_name': 'История справок за период',
                'ordering': ['sequence_number'],
            },
        ),
    ]
