# Generated by Django 4.2.20 on 2025-09-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryperiod',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Справка за период'},
        ),
    ]
