# Generated by Django 4.2.20 on 2025-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_enquiryperiod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryperiod',
            options={'ordering': ['-sequence_number'], 'verbose_name': 'Справка за период', 'verbose_name_plural': 'Справки за период'},
        ),
    ]
