# Generated by Django 4.2.20 on 2025-10-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_enquiryperiod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryperiod',
            options={'ordering': ['-sequence_number'], 'verbose_name': 'Справка по сообщениям за период', 'verbose_name_plural': 'Справки по сообщениям за период'},
        ),
    ]
